### ISSUE TITLE
[BUG] SonarCloud Bug - Correct one of the identical sub-expressions on both sides of operator "=="

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#11]
tests/victoria_email/test_request_body.py

L37

`assert 1 == 1`

https://sonarcloud.io/project/issues?id=victoria-email&issues=AXUI_GWLdY21KIBnigUH&open=AXUI_GWLdY21KIBnigUH

**Comment by AshKapow** [comment]
![Screenshot 2021-02-18 at 12 09 14](https://user-images.githubusercontent.com/3803158/108355000-1f809480-71e2-11eb-8930-bd8fc69a0a5f.png)

**Comment by mukulgupta2138** [comment]
Created PR for this https://github.com/glasswall-sre/victoria_email/pull/56

**Comment by AshKapow** [comment]
@mukulgupta2138 confirmed as resolved in SonarCloud
