### ISSUE TITLE
[BUG] SonarCloud Bug - Correct one of the identical sub-expressions on both sides of operator "=="

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#12]
tests/victoria_email/test_request_body.py

L75

`assert 1 == 1`

https://sonarcloud.io/project/issues?id=victoria-email&issues=AXUI_GWLdY21KIBnigUL&open=AXUI_GWLdY21KIBnigUL

**Comment by AshKapow** [comment]
![Screenshot 2021-02-18 at 12 07 54](https://user-images.githubusercontent.com/3803158/108354922-0a0b6a80-71e2-11eb-9127-cff4d64592f2.png)

**Comment by mukulgupta2138** [comment]
Created PR for this https://github.com/glasswall-sre/victoria_email/pull/56

**Comment by AshKapow** [comment]
@mukulgupta2138 confirmed as resolved in SonarCloud
