### ISSUE TITLE
[BUG] Unable to Reconstruct - Reconstruct Location

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#38]
**Is your feature request related to a problem? Please describe.**
This is slightly related to the issue documented in #37 

**Describe the solution you'd like**
Unable to specify wether to query a Storage Blob or a Service Bus Queue for reconstructing mail

**Additional context**
Something along the lines of (for example):
`victoria email reconstruct -servicebus dev -i <guid> -o output_dir`
and
`victoria email reconstruct -storageblob dev -i <guid> -o output_dir`

**Comment by mukulgupta2138** [comment]
Created PR for this https://github.com/glasswall-sre/victoria_email/pull/51
