### ISSUE TITLE
[REQUEST] Add AZURE_STORAGE_CONNECTION_STRING to config file

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#39]
**Describe the solution you'd like**
We currently need to specify an Azure connection string for the connection to Going Postal for the loadtest feature. It would be nicer if we could specify this in the email.yml config that sits in the Azure centralised config.

**Specific Details**
In PowerShell we need to add
`export AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=slsgoingpostalattachment;AccountKey=***;EndpointSuffix=core.windows.net"`
In Linux we need to add
`$AZURE_STORAGE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=slsgoingpostalattachment;AccountKey=***;EndpointSuffix=core.windows.net"`

**Comment by mukulgupta2138** [comment]
Created a PR for this https://github.com/glasswall-sre/victoria_email/pull/46
