### ISSUE TITLE
[REQUEST] Encrypt any Connection Strings within the config

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#47]
**Describe the solution you'd like**
Sections of the config such as "load_test/attachments/storage_connection_strings", "mail_toil/service_bus_connection_strings", and "mail_toil/storage_accounts" are currently clear text. These will need to be able to be encrypted by the Victoria Encryption functionality `victoria encrypt data`

Please speak to @AshKapow or see the emailencrypted.yaml config for more information

**Comment by mukulgupta2138** [comment]
Created PR for this https://github.com/glasswall-sre/victoria_email/pull/53

**Comment by mukulgupta2138** [comment]
Marking as done
